name: Build npm

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
  
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK Windows
        uses: actions/setup-java@v2
        if: matrix.os == 'windows-latest'
        with:
          java-version: 11
          java-package: 'jdk'
          architecture: 'x64'
          distribution: 'adopt'
      - name: Install Java ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get remove adoptopenjdk* -y && sudo apt-get install -y openjdk-11-jdk

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          languages: java, javascript

      # Steps for getting the name for this artifact
      # The artifact name has the following format:
      # docman-${LATEST_RELEASE_TAG}-beta.YYYYmmdd-1HHMMSS
      - name: Get latest release tag
        id: latest_release
        run: echo "::set-output name=release::$(node -p 'require(`./package.json`).version')"
        shell: bash
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d.1%H%M%S')"
        shell: bash
      - name: Set version name
        id: version_name
        run: echo "::set-output name=version::docman-${{steps.latest_release.outputs.release}}-beta.${{steps.date.outputs.date}}"
        shell: bash
      - name: Print version name
        run: echo ${{steps.version_name.outputs.version}}
        shell: bash

      # Set the docman package version using npm
      - name: Set docman version
        run: npm version --no-git-tag-version ${{steps.latest_release.outputs.release}}-beta.${{steps.date.outputs.date}} -f

      # npm install
      - name: npm install
        run: npm ci
      - name: Package
        run: npm run pack
        env:
          GH_TOKEN: ${{secrets.github_token}}

      # Upload the artifact
      - name: Upload beta build windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{steps.version_name.outputs.version}}_win64
          path: dist/docman-v${{steps.latest_release.outputs.release}}-beta.${{steps.date.outputs.date}}.exe

      - name: Upload beta build snap
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{steps.version_name.outputs.version}}_snap
          path: dist/docman*.snap
      - name: Upload beta build deb
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{steps.version_name.outputs.version}}_deb
          path: dist/docman*.deb
      - name: Upload beta build AppImage
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{steps.version_name.outputs.version}}_AppImage
          path: dist/docman*.AppImage

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        if: matrix.os == 'ubuntu-latest'
