name: Build npm

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm ci
    - name: build
      run: npm run build
